//! Durable, local recovery breadcrumbs for opt-in destructive VTN probes.
//! Each run writes a private append-only text journal BEFORE issuing CREATE.
//! The journal is not a transaction log and does not perform recovery itself.

use std::{
    fs::{File, OpenOptions},
    io::{self, Write},
    path::PathBuf,
};

pub struct RecoveryJournal {
    file: File,
    pub path: PathBuf,
}

impl RecoveryJournal {
    pub fn begin(kind: &str, name: &str, url: &str) -> io::Result<Self> {
        let dir = std::env::var_os("OPENLEADR_RS_RECOVERY_DIR")
            .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidInput,
                "OPENLEADR_RS_RECOVERY_DIR must point to a private durable directory"))?;
        Self::begin_in(PathBuf::from(dir), kind, name, url)
    }

    fn begin_in(dir: PathBuf, kind: &str, name: &str, url: &str) -> io::Result<Self> {
        if !dir.is_dir() {
            return Err(io::Error::new(io::ErrorKind::NotFound,
                "recovery directory must exist before running mutating tests"));
        }
        // Both parts are generated by our tests. Reject arbitrary path segments.
        if !name.chars().all(|c| c.is_ascii_alphanumeric() || c == '-')
            || !kind.chars().all(|c| c.is_ascii_alphabetic())
        {
            return Err(io::Error::new(io::ErrorKind::InvalidInput, "invalid journal identifier"));
        }
        let path = dir.join(format!("{kind}-{name}.log"));
        let file = OpenOptions::new().write(true).create_new(true).open(&path)?;
        let mut journal = Self { file, path };
        journal.record(&format!("BEGIN name={name} url={url}"))?;
        // fsync the directory entry as well as the file before remote CREATE.
        File::open(&dir)?.sync_all()?;
        Ok(journal)
    }

    pub fn record(&mut self, message: &str) -> io::Result<()> {
        writeln!(self.file, "{message}")?;
        self.file.sync_all()
    }
}

#[cfg(test)]
mod tests {
    use super::RecoveryJournal;
    use std::{fs, path::PathBuf};
    use uuid::Uuid;

    struct TestDir(PathBuf);

    impl TestDir {
        fn new() -> Self {
            let path = std::env::temp_dir()
                .join(format!("openleadr-journal-test-{}", Uuid::new_v4()));
            fs::create_dir(&path).expect("create test journal directory");
            Self(path)
        }
    }

    impl Drop for TestDir {
        fn drop(&mut self) {
            fs::remove_dir_all(&self.0).expect("remove test journal directory");
        }
    }

    #[test]
    fn reject_unsafe_names_in_real_directory() {
        let dir = TestDir::new();
        assert!(RecoveryJournal::begin_in(dir.0.clone(), "Program", "../unsafe", "https://example.test/").is_err());
        assert!(RecoveryJournal::begin_in(dir.0.clone(), "../Event", "safe", "https://example.test/").is_err());
        assert_eq!(fs::read_dir(&dir.0).unwrap().count(), 0);
    }

    #[test]
    fn persist_intent_and_refuse_duplicate_run() {
        let dir = TestDir::new();
        let mut journal = RecoveryJournal::begin_in(
            dir.0.clone(), "Program", "probe-123", "https://example.test/"
        ).expect("begin journal");
        journal.record("PROGRAM_CREATE_ATTEMPT").expect("sync intent");
        let path = journal.path.clone();
        drop(journal);

        let recorded = fs::read_to_string(&path).expect("read persisted journal");
        assert!(recorded.contains("BEGIN name=probe-123 url=https://example.test/"));
        assert!(recorded.contains("PROGRAM_CREATE_ATTEMPT"));
        assert!(RecoveryJournal::begin_in(
            dir.0.clone(), "Program", "probe-123", "https://example.test/"
        ).is_err(), "existing log must never be truncated");
        assert_eq!(fs::read_to_string(&path).unwrap(), recorded);
    }

    #[test]
    fn missing_directory_fails_closed() {
        let dir = TestDir::new();
        let absent = dir.0.join("missing");
        assert!(RecoveryJournal::begin_in(absent, "Program", "probe", "https://example.test/").is_err());
    }
}
