//! Durable, local recovery breadcrumbs for opt-in destructive VTN probes.
//! Each run writes a private append-only text journal BEFORE issuing CREATE.
//! The journal is not a transaction log and does not perform recovery itself.

use std::{
    fs::{File, OpenOptions},
    io::{self, Write},
    path::PathBuf,
};

pub struct RecoveryJournal {
    file: File,
    pub path: PathBuf,
}

impl RecoveryJournal {
    pub fn begin(kind: &str, name: &str, url: &str) -> io::Result<Self> {
        let dir = std::env::var_os("OPENLEADR_RS_RECOVERY_DIR")
            .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidInput,
                "OPENLEADR_RS_RECOVERY_DIR must point to a private durable directory"))?;
        let dir = PathBuf::from(dir);
        if !dir.is_dir() {
            return Err(io::Error::new(io::ErrorKind::NotFound,
                "recovery directory must exist before running mutating tests"));
        }
        // Both parts are generated by our tests. Reject arbitrary path segments.
        if !name.chars().all(|c| c.is_ascii_alphanumeric() || c == '-')
            || !kind.chars().all(|c| c.is_ascii_alphabetic())
        {
            return Err(io::Error::new(io::ErrorKind::InvalidInput, "invalid journal identifier"));
        }
        let path = dir.join(format!("{kind}-{name}.log"));
        let file = OpenOptions::new().write(true).create_new(true).open(&path)?;
        let mut journal = Self { file, path };
        journal.record(&format!("BEGIN name={name} url={url}"))?;
        // fsync the directory entry as well as the file before remote CREATE.
        File::open(&dir)?.sync_all()?;
        Ok(journal)
    }

    pub fn record(&mut self, message: &str) -> io::Result<()> {
        writeln!(self.file, "{message}")?;
        self.file.sync_all()
    }
}

#[cfg(test)]
mod tests {
    use super::RecoveryJournal;
    #[test]
    fn reject_missing_directory_and_unsafe_filename() {
        let bad = RecoveryJournal::begin("Program", "../unsafe", "https://example.test/");
        assert!(bad.is_err());
    }
}
